mod 'puppet-nginx', '3.3.0'
mod 'puppetlabs-concat', '7.1.1'
mod 'puppetlabs-stdlib', '8.1.0'
mod 'puppetlabs-docker', '4.1.2'
mod 'puppetlabs-apt', '8.3.0'
mod 'puppetlabs-powershell', '5.0.0'
mod 'puppetlabs-reboot', '4.1.0'
